### ISSUE TITLE
Craft 4 / Commerce 4 compatibility?

### ISSUE THREAD

**Issue by imagehat** [jmauzyk/commerce-cardconnect#1]
I'm wondering if this plugin will work with Craft/Commerce 4 or if you have plans to update. We've got an upcoming site that we'd like to use this gateway for. Thanks!

**Comment by jmauzyk** [comment]
I was just looking at marking this plugin as abandoned. My employer moved away from this gateway a while ago, and the Craft ID dashboard currently shows 0 active installs, so I have no plans to continue development with this. I'd be happy to hand over ownership to you guys if that's something you're interested in.

**Comment by imagehat** [comment]
Thanks very much for letting us know. For now I just forked the repo in case we do move ahead with a Craft 4 update. I'm not sure we'd want to support the public plugin, at least for now, but thank you and we'll keep that in mind. Also thanks for all your great work on this and the Omnipay adapter!
